debug = true
output_file_path = "~/LX-Scanner/output"

[rabbitmq]

input-queue = "model-input"
output-queue = "model-output"

[rabbitmq.dev]
username = "guest"
password = "guest"
host = "localhost"
port = 5672
vhost = "/"

[rabbitmq.prod]
username = "guest"
password = "guest"
host = "localhost"
port = 5672
vhost = "/"
queue = "queue"