debug = true
#output_file_path = "/srv/LX-Scanner/output"

[rabbitmq]

[rabbitmq.dev]
username = "guest"
password = "guest"
host = "localhost"
port = 5672
vhost = "/"
queue = "queue"

[rabbitmq.prod]
username = "guest"
password = "guest"
host = "localhost"
port = 5672
vhost = "/"
queue = "queue"